"""Create initial schema

Revision ID: f9fda2306f8a
Revises:
Create Date: 2026-09-09 03:37:46.808887
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f9fda2306f8a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cin", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("legal_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("incorporation_date", sa.Date(), nullable=True),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column("lifecycle_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_company_cin"), "company", ["cin"], unique=True)
    op.create_table(
        "person",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("din", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("normalized_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_person_din"), "person", ["din"], unique=True)
    op.create_index(op.f("ix_person_normalized_name"), "person", ["normalized_name"], unique=False)
    op.create_table(
        "source",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cadence", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("health_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_source_key"), "source", ["key"], unique=True)
    op.create_table(
        "tenant",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("thesis_doc", sa.Text(), nullable=True),
        sa.Column("weight_overrides", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "company_alias",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("normalized_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("first_seen_source_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.ForeignKeyConstraint(
            ["first_seen_source_id"],
            ["source.id"],
        ),
        sa.PrimaryKeyConstraint("company_id", "normalized_name"),
    )
    op.create_index(
        op.f("ix_company_alias_normalized_name"), "company_alias", ["normalized_name"], unique=False
    )
    op.create_table(
        "company_person",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_ref", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0.0 AND confidence <= 1.0", name="ck_company_person_confidence_range"
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
        ),
        sa.PrimaryKeyConstraint("company_id", "person_id", "role"),
    )
    op.create_table(
        "raw_doc",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_raw_doc_content_hash"), "raw_doc", ["content_hash"], unique=True)
    op.create_index(op.f("ix_raw_doc_source_id"), "raw_doc", ["source_id"], unique=False)
    op.create_table(
        "review_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('interesting', 'not_for_us', 'already_known', 'data_wrong')",
            name="ck_review_event_action",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_event_company_id"), "review_event", ["company_id"], unique=False
    )
    op.create_index(op.f("ix_review_event_tenant_id"), "review_event", ["tenant_id"], unique=False)
    op.create_table(
        "score",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("total", sa.Float(), nullable=False),
        sa.Column("components", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("total >= 0.0 AND total <= 100.0", name="ck_score_total_range"),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("company_id", "tenant_id"),
    )
    op.create_table(
        "signal",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("signal_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_doc_id", sa.Uuid(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("extractor_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0.0 AND confidence <= 1.0", name="ck_signal_confidence_range"
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.ForeignKeyConstraint(
            ["raw_doc_id"],
            ["raw_doc.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_signal_company_id"), "signal", ["company_id"], unique=False)
    op.create_index(op.f("ix_signal_raw_doc_id"), "signal", ["raw_doc_id"], unique=False)
    op.create_index(op.f("ix_signal_signal_type"), "signal", ["signal_type"], unique=False)
    op.create_index(op.f("ix_signal_source_id"), "signal", ["source_id"], unique=False)
    op.create_table(
        "resolution_candidate",
        sa.Column("signal_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("match_score", sa.Float(), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("decided_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "match_score >= 0.0 AND match_score <= 1.0",
            name="ck_resolution_candidate_match_score_range",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signal.id"],
        ),
        sa.PrimaryKeyConstraint("signal_id", "company_id"),
    )
    op.create_table(
        "watchlist",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("awarding_signal_id", sa.Uuid(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["awarding_signal_id"],
            ["signal.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_watchlist_awarding_signal_id"), "watchlist", ["awarding_signal_id"], unique=True
    )
    op.create_index(op.f("ix_watchlist_person_id"), "watchlist", ["person_id"], unique=False)
    op.create_index(op.f("ix_watchlist_status"), "watchlist", ["status"], unique=False)
    op.execute(
        """
        CREATE FUNCTION reject_immutable_table_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION '% is immutable; % is not allowed', TG_TABLE_NAME, TG_OP
                USING ERRCODE = '55000';
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER raw_doc_immutable
        BEFORE UPDATE OR DELETE ON raw_doc
        FOR EACH ROW
        EXECUTE FUNCTION reject_immutable_table_mutation()
        """
    )
    op.execute(
        """
        CREATE TRIGGER signal_append_only
        BEFORE UPDATE OF
            id,
            signal_type,
            source_id,
            event_date,
            payload,
            raw_doc_id,
            confidence,
            extractor_version,
            created_at
        OR DELETE ON signal
        FOR EACH ROW
        EXECUTE FUNCTION reject_immutable_table_mutation()
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS signal_append_only ON signal")
    op.execute("DROP TRIGGER IF EXISTS raw_doc_immutable ON raw_doc")
    op.execute("DROP FUNCTION IF EXISTS reject_immutable_table_mutation()")
    op.drop_index(op.f("ix_watchlist_status"), table_name="watchlist")
    op.drop_index(op.f("ix_watchlist_person_id"), table_name="watchlist")
    op.drop_index(op.f("ix_watchlist_awarding_signal_id"), table_name="watchlist")
    op.drop_table("watchlist")
    op.drop_table("resolution_candidate")
    op.drop_index(op.f("ix_signal_source_id"), table_name="signal")
    op.drop_index(op.f("ix_signal_signal_type"), table_name="signal")
    op.drop_index(op.f("ix_signal_raw_doc_id"), table_name="signal")
    op.drop_index(op.f("ix_signal_company_id"), table_name="signal")
    op.drop_table("signal")
    op.drop_table("score")
    op.drop_index(op.f("ix_review_event_tenant_id"), table_name="review_event")
    op.drop_index(op.f("ix_review_event_company_id"), table_name="review_event")
    op.drop_table("review_event")
    op.drop_index(op.f("ix_raw_doc_source_id"), table_name="raw_doc")
    op.drop_index(op.f("ix_raw_doc_content_hash"), table_name="raw_doc")
    op.drop_table("raw_doc")
    op.drop_table("company_person")
    op.drop_index(op.f("ix_company_alias_normalized_name"), table_name="company_alias")
    op.drop_table("company_alias")
    op.drop_table("tenant")
    op.drop_index(op.f("ix_source_key"), table_name="source")
    op.drop_table("source")
    op.drop_index(op.f("ix_person_normalized_name"), table_name="person")
    op.drop_index(op.f("ix_person_din"), table_name="person")
    op.drop_table("person")
    op.drop_index(op.f("ix_company_cin"), table_name="company")
    op.drop_table("company")
    # ### end Alembic commands ###
